create table if not exists public.lessons (id bigint generated by default as identity primary key,date date not null,lesson_number int not null check (lesson_number between 1 and 6),time text not null,subject text not null,teacher text default '',room text default '',type text default '',remote boolean default false);
alter table public.lessons enable row level security;
drop policy if exists "public can read lessons" on public.lessons; drop policy if exists "authenticated can insert lessons" on public.lessons; drop policy if exists "authenticated can update lessons" on public.lessons; drop policy if exists "authenticated can delete lessons" on public.lessons;
create policy "public can read lessons" on public.lessons for select to anon, authenticated using (true);
create policy "authenticated can insert lessons" on public.lessons for insert to authenticated with check (true);
create policy "authenticated can update lessons" on public.lessons for update to authenticated using (true) with check (true);
create policy "authenticated can delete lessons" on public.lessons for delete to authenticated using (true);
